
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module challenge(
	input 		          		CLOCK_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,

	output		     [8:0]		LEDG,
	output		    [17:0]		LEDR,

	input 		     [3:0]		KEY,

	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,
	output		     [6:0]		HEX6,
	output		     [6:0]		HEX7
);

  wire unc0;
  wire unc1;
  wire unc2;
  wire unc3;
  wire unc4;
  wire unc5;
  wire unc6;
  wire unc7;
  wire [4:0] uncG;

  challengeqsys u0 (
        .clk_clk                          (CLOCK_50),   
        .pio_0_external_connection_export ({unc3,HEX3, unc2,HEX2, unc1,HEX1, unc0,HEX0}),
        .pio_1_external_connection_export ({unc7,HEX7, unc6,HEX6, unc5,HEX5, unc4,HEX4}),
		  .pio_2_external_connection_export ({uncG,LEDG[8:0],LEDR[17:0]}),
        .reset_reset_n                    (KEY[0]) 
    );

endmodule
